<?php include 'header.php'; ?>
					<main >
						<h1 class='decalTitre'>Mentions légales</h1>
						<section class='mentions'>
							<article>
								<h2>Siège social</h2>
								<p>Entreprise individuelle</p>
								<p>Numéro de SIRET : 431 303 775 666 16</p>
								<p class='picto'><i class="fas fa-map-marker"></i> 6 Avenue Halley, 59650 Villeneuve d'Ascq</p>
								<p>Consulter notre <a href="politique-de-confidentialite.html">Politique de confidentialité</a>.</p>
							</article>
							<article>
								<h2>Éditeur du site</h2>
								<h3>IFOCOP</h3>
								
								<p class='picto'><i class="fas fa-map-marker"></i> 27 Rue Denis Papin</p> 
								<p>59650 Villeneuve-d'Ascq</p>
								<p class='picto'> <i class="fas fa-phone"> </i><a href="tel:+3320476092">03 20 47 60 92</a> </p>
								
							</article>
							<article>
								<h2>Hébergement du site</h2>
								<p>OVH</p>
								<address>
									<p>2 rue Kellermann</p>
									<p>59100 ROUBAIX</p>
								</address>
								<p>Site web : <a href='www.ovh.com'>www.ovh.com</a></p>
							</article>
						</section>
					</main>
	<?php include 'footer.php'; ?>