<?php include 'header.php'; ?>
					<main>
						<section>
						<h1>Politique de confidentialité</h1>
						<h2>Données personnelles</h2>

						<p>Conformément au Règlement Général sur la Protection des Données (GRPD) adopté par le Parlement européen le 14 avril 2016, nous vous informons des points suivants :</p>
						<h2>Identité du responsable du traitement</h2>

						<p>Le responsable du traitement des données pour ce site internet est :</p>

						<p>Madame Stéphanie DESSART</p>
							<p class='picto'><i class="fas fa-map-marker"></i> 6 Avenue Halley</p>
							<p>59650 Villeneuve d'Ascq</p>
							<p class='picto'><i class="fas fa-phone"> </i> Téléphone : <a class ='nostyle' href="tel:+33662727500">06 62 72 75 00</a></p>
						<h2>Finalités du traitement</h2>

						<p>Les informations recueillies sur le site via les formulaires sont destinées à pouvoir rentrer en contact avec vous et à vous envoyer notre newsletter.</p>
						<h2>Destinataires</h2>

						<p>Les données collectées sur ce site ne sont pas transmises à des tiers, nonobstant les sous-traitants informatiques auxquels l'entreprise peut faire appel.</p>

						<p>Ni l'entreprise, ni ses sous-traitants, ne procèdent à la commercialisation des données personnelles des visiteurs et utilisateurs de ce site.</p>
						<h2>Durée de conservation</h2>

						<p>Les données collectées sur ce site sont conservées pendant une durée maximale de 12 mois en cas de non conclusion d’une prestation.</p>
						<h2>Droit d’accès et de rectification des données</h2>

						<p>Nous vous donnons un droit d’accès pour consulter, modifier, ou effacer les informations vous concernant.</p>

						<p>Cependant, en raison de l’obligation de sécurité et de confidentialité dans le traitement des données à caractère personnel qui nous incombe, vous êtes informé que votre demande sera traitée sous réserve que vous apportiez la preuve de votre identité, notamment par la production d’une copie de votre titre d’identité valide.</p>

						<p>Pour pouvoir exercer ces droits, vous devez adresser votre demande par écrit au responsable du traitement.</p>
						<h2>Droit d’opposition</h2>

						<p>L’exercice de ce droit est possible dès lors que ce droit vise à faire obstacle à des fins de prospection commerciale, notamment l’envoi des newsletters.</p>
						<h2>Délai de réponse</h2>

						<p>Nous nous engageons à répondre à votre demande d’accès, de rectification ou d’opposition ou toute autre demande complémentaire d’informations dans un délai raisonnable qui ne saurait dépasser 1 mois à compter de la réception de votre demande.</p>
</section>
					</main>
		<?php include 'footer.php'; ?>